
package com.coronation.upload.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EntrustMultiFactorAuthImpl", targetNamespace = "http://ws.entrustplugin.expertedge.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EntrustMultiFactorAuthImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AuthResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performTokenAuthCorporateNoCategory", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformTokenAuthCorporateNoCategory")
    @ResponseWrapper(localName = "performTokenAuthCorporateNoCategoryResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformTokenAuthCorporateNoCategoryResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthCorporateNoCategoryRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthCorporateNoCategoryResponse")
    public AuthResponseDTO performTokenAuthCorporateNoCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        TokenAuthCorporateDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AuthResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performIpGeoLocationAuth", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformIpGeoLocationAuth")
    @ResponseWrapper(localName = "performIpGeoLocationAuthResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformIpGeoLocationAuthResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performIpGeoLocationAuthRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performIpGeoLocationAuthResponse")
    public AuthResponseDTO performIpGeoLocationAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        IpGeoAuthDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performCreateEntrustUser", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformCreateEntrustUser")
    @ResponseWrapper(localName = "performCreateEntrustUserResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformCreateEntrustUserResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateEntrustUserRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateEntrustUserResponse")
    public AdminResponseDTO performCreateEntrustUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdminDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.QaSizeResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performGetMinQASize", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformGetMinQASize")
    @ResponseWrapper(localName = "performGetMinQASizeResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformGetMinQASizeResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetMinQASizeRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetMinQASizeResponse")
    public QaSizeResponseDTO performGetMinQASize(
        @WebParam(name = "arg0", targetNamespace = "")
        QaGetDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.ActivateSoftTokenResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performActivateSoftToken", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformActivateSoftToken")
    @ResponseWrapper(localName = "performActivateSoftTokenResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformActivateSoftTokenResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performActivateSoftTokenRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performActivateSoftTokenResponse")
    public ActivateSoftTokenResponseDTO performActivateSoftToken(
        @WebParam(name = "arg0", targetNamespace = "")
        ActivateSoftTokenDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.ActivateCompleteSoftTokenResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performActivateCompleteSoftToken", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformActivateCompleteSoftToken")
    @ResponseWrapper(localName = "performActivateCompleteSoftTokenResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformActivateCompleteSoftTokenResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performActivateCompleteSoftTokenRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performActivateCompleteSoftTokenResponse")
    public ActivateCompleteSoftTokenResponseDTO performActivateCompleteSoftToken(
        @WebParam(name = "arg0", targetNamespace = "")
        ActivateCompleteSoftTokenDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AuthMutResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performSetMutualAuth", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformSetMutualAuth")
    @ResponseWrapper(localName = "performSetMutualAuthResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformSetMutualAuthResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetMutualAuthRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetMutualAuthResponse")
    public AuthMutResponseDTO performSetMutualAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        SetMutualSecretRespDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AuthMutResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performSetMutualAuthX", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformSetMutualAuthX")
    @ResponseWrapper(localName = "performSetMutualAuthXResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformSetMutualAuthXResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetMutualAuthXRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetMutualAuthXResponse")
    public AuthMutResponseDTO performSetMutualAuthX(
        @WebParam(name = "arg0", targetNamespace = "")
        SetMutualSecretXDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AuthMutResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performSetMutualAuth2", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformSetMutualAuth2")
    @ResponseWrapper(localName = "performSetMutualAuth2Response", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformSetMutualAuth2Response")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetMutualAuth2Request", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetMutualAuth2Response")
    public AuthMutResponseDTO performSetMutualAuth2(
        @WebParam(name = "arg0", targetNamespace = "")
        SetMutualSecretDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performDeleteEntrustUser", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformDeleteEntrustUser")
    @ResponseWrapper(localName = "performDeleteEntrustUserResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformDeleteEntrustUserResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performDeleteEntrustUserRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performDeleteEntrustUserResponse")
    public AdminResponseDTO performDeleteEntrustUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserDelAdminDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performUpdateEntrustUser", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformUpdateEntrustUser")
    @ResponseWrapper(localName = "performUpdateEntrustUserResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformUpdateEntrustUserResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performUpdateEntrustUserRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performUpdateEntrustUserResponse")
    public AdminResponseDTO performUpdateEntrustUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAdminDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.CreateSoftTokenResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performCreateSoftToken", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformCreateSoftToken")
    @ResponseWrapper(localName = "performCreateSoftTokenResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformCreateSoftTokenResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateSoftTokenRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateSoftTokenResponse")
    public CreateSoftTokenResponseDTO performCreateSoftToken(
        @WebParam(name = "arg0", targetNamespace = "")
        CreateSoftTokenDTO arg0);

    /**
     * 
     * @return
     *     returns com.coronation.upload.ws.SoftTokenOnBoardingProcessResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSoftTokenOnBoardingProcess", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.GetSoftTokenOnBoardingProcess")
    @ResponseWrapper(localName = "getSoftTokenOnBoardingProcessResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.GetSoftTokenOnBoardingProcessResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/getSoftTokenOnBoardingProcessRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/getSoftTokenOnBoardingProcessResponse")
    public SoftTokenOnBoardingProcessResponseDTO getSoftTokenOnBoardingProcess();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.TokenSerialResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performGetTokenSerial", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformGetTokenSerial")
    @ResponseWrapper(localName = "performGetTokenSerialResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformGetTokenSerialResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetTokenSerialRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetTokenSerialResponse")
    public TokenSerialResponseDTO performGetTokenSerial(
        @WebParam(name = "arg0", targetNamespace = "")
        TokenSerialDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AuthResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performCreateSendOTP", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformCreateSendOTP")
    @ResponseWrapper(localName = "performCreateSendOTPResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformCreateSendOTPResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateSendOTPRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateSendOTPResponse")
    public AuthResponseDTO performCreateSendOTP(
        @WebParam(name = "arg0", targetNamespace = "")
        OtpCreateSendDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AuthResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performOTPAuthentication", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformOTPAuthentication")
    @ResponseWrapper(localName = "performOTPAuthenticationResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformOTPAuthenticationResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performOTPAuthenticationRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performOTPAuthenticationResponse")
    public AuthResponseDTO performOTPAuthentication(
        @WebParam(name = "arg0", targetNamespace = "")
        OtpAuthDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.ImageCaptionResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performGetMutualAuth", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformGetMutualAuth")
    @ResponseWrapper(localName = "performGetMutualAuthResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformGetMutualAuthResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetMutualAuthRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetMutualAuthResponse")
    public ImageCaptionResponseDTO performGetMutualAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        MauthDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performAssignToken", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformAssignToken")
    @ResponseWrapper(localName = "performAssignTokenResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformAssignTokenResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performAssignTokenRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performAssignTokenResponse")
    public AdminResponseDTO performAssignToken(
        @WebParam(name = "arg0", targetNamespace = "")
        TokenAdminDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performUnLockUser", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformUnLockUser")
    @ResponseWrapper(localName = "performUnLockUserResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformUnLockUserResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performUnLockUserRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performUnLockUserResponse")
    public AdminResponseDTO performUnLockUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserUnLockDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AuthResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performTokenAuthNoCategory", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformTokenAuthNoCategory")
    @ResponseWrapper(localName = "performTokenAuthNoCategoryResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformTokenAuthNoCategoryResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthNoCategoryRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthNoCategoryResponse")
    public AuthResponseDTO performTokenAuthNoCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        TokenAuthDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performDeactivateToken", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformDeactivateToken")
    @ResponseWrapper(localName = "performDeactivateTokenResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformDeactivateTokenResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performDeactivateTokenRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performDeactivateTokenResponse")
    public AdminResponseDTO performDeactivateToken(
        @WebParam(name = "arg0", targetNamespace = "")
        TokenAdminDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AuthResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performPasswordAuth", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformPasswordAuth")
    @ResponseWrapper(localName = "performPasswordAuthResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformPasswordAuthResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performPasswordAuthRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performPasswordAuthResponse")
    public AuthResponseDTO performPasswordAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        PasswordAuthDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performAddContactDetail", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformAddContactDetail")
    @ResponseWrapper(localName = "performAddContactDetailResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformAddContactDetailResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performAddContactDetailRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performAddContactDetailResponse")
    public AdminResponseDTO performAddContactDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        UserContactDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performUnassignToken", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformUnassignToken")
    @ResponseWrapper(localName = "performUnassignTokenResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformUnassignTokenResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performUnassignTokenRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performUnassignTokenResponse")
    public AdminResponseDTO performUnassignToken(
        @WebParam(name = "arg0", targetNamespace = "")
        TokenAdminDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.ImageCaptionResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performMutualAuth", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformMutualAuth")
    @ResponseWrapper(localName = "performMutualAuthResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformMutualAuthResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performMutualAuthRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performMutualAuthResponse")
    public ImageCaptionResponseDTO performMutualAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        MauthDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performActivateToken", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformActivateToken")
    @ResponseWrapper(localName = "performActivateTokenResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformActivateTokenResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performActivateTokenRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performActivateTokenResponse")
    public AdminResponseDTO performActivateToken(
        @WebParam(name = "arg0", targetNamespace = "")
        TokenAdminDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performSoftTokenSync", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformSoftTokenSync")
    @ResponseWrapper(localName = "performSoftTokenSyncResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformSoftTokenSyncResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSoftTokenSyncRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSoftTokenSyncResponse")
    public AdminResponseDTO performSoftTokenSync(
        @WebParam(name = "arg0", targetNamespace = "")
        SoftTokenSynDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.QaGetResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performGetQA", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformGetQA")
    @ResponseWrapper(localName = "performGetQAResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformGetQAResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetQARequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetQAResponse")
    public QaGetResponseDTO performGetQA(
        @WebParam(name = "arg0", targetNamespace = "")
        QaGetDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AuthResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performTokenAuth", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformTokenAuth")
    @ResponseWrapper(localName = "performTokenAuthResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformTokenAuthResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthResponse")
    public AuthResponseDTO performTokenAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        TokenAuthDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.QaSizeResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performGetQASize", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformGetQASize")
    @ResponseWrapper(localName = "performGetQASizeResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformGetQASizeResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetQASizeRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performGetQASizeResponse")
    public QaSizeResponseDTO performGetQASize(
        @WebParam(name = "arg0", targetNamespace = "")
        QaGetDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performSetQA", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformSetQA")
    @ResponseWrapper(localName = "performSetQAResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformSetQAResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetQARequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performSetQAResponse")
    public AdminResponseDTO performSetQA(
        @WebParam(name = "arg0", targetNamespace = "")
        QaSetDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AuthResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performReSendOTP", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformReSendOTP")
    @ResponseWrapper(localName = "performReSendOTPResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformReSendOTPResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performReSendOTPRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performReSendOTPResponse")
    public AuthResponseDTO performReSendOTP(
        @WebParam(name = "arg0", targetNamespace = "")
        OtpCreateSendDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performTokenSync", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformTokenSync")
    @ResponseWrapper(localName = "performTokenSyncResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformTokenSyncResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenSyncRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenSyncResponse")
    public AdminResponseDTO performTokenSync(
        @WebParam(name = "arg0", targetNamespace = "")
        TokenSynDTO arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pingEntrustConn", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PingEntrustConn")
    @ResponseWrapper(localName = "pingEntrustConnResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PingEntrustConnResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/pingEntrustConnRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/pingEntrustConnResponse")
    public String pingEntrustConn();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.coronation.upload.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performCreateOTP", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformCreateOTP")
    @ResponseWrapper(localName = "performCreateOTPResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.coronation.upload.ws.PerformCreateOTPResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateOTPRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateOTPResponse")
    public AdminResponseDTO performCreateOTP(
        @WebParam(name = "arg0", targetNamespace = "")
        OtpCreateDTO arg0);

}
